### ISSUE TITLE
4.2.3.2 Web API. parentNode vs parentElement

### ISSUE THREAD

**Issue by AleshaOleg** [rnicholus/beyond-jquery-book#10]
Here is a loop I found in book:
```
var currentNode = document.getElementsByTagName('a')[0], ancestors = [];

while (currentNode.parentNode) {
	ancestors.push(currentNode.parentElement);
	currentNode = currentNode.parentElement;
}
```
And it works wrong. If we debug that one, we can found that every element from out DOM will be added. But last will be `null` and that exception `Uncaught TypeError: Cannot read property 'parentNode' of null`. I propose to use:

`while (currentNode.parentElement)` - with this, everything works fine!

As I understood, we can't use `.parentNode()` in loops.

**Comment by AleshaOleg** [comment]
By the way, we can use `parentNode` everywhere, like this:

```
var currentNode = document.getElementsByTagName('a')[0], ancestors = [];

while (currentNode) {
	ancestors.push(currentNode.parentNode);
	currentNode = currentNode.parentNode;
}

console.log(ancestors);
```

But the last one will be a `null`.

**Comment by rnicholus** [comment]
I'll have to look closer later, but it seems like you found another typo.
Thanks again! These are bound to happen as I do not have an editor for the
book, so I am forced to edit myself as best I can.

**Comment by rnicholus** [comment]
Fixed and I just published a revised version.
