### ISSUE TITLE
Chapter 7, page 110, typo in code

### ISSUE THREAD

**Issue by AleshaOleg** [rnicholus/beyond-jquery-book#12]
There is a code from book.

```
stylesheet.insertRule(
    'h2 { font-weight: italic; }', stylesheet.cssRules.length - 1
);
```

And there is no such value `italic` for `font-weight`. There, should be a `font-style` property.

Final result:

```
stylesheet.insertRule (
	'h2{ font-style: italic }', stylesheet.cssRules.length - 1
);
```

**Comment by rnicholus** [comment]
Thanks for catching this typo! I believe the original style was to be "bold". That case, `font-weight` would be appropriate, but I must have switched it to "italic" at some point and forgot to change the property as well. I'll fix this when ch 11 is published.
