### ISSUE TITLE
Chapter 7, page 110, no 'stylesheet' value

### ISSUE THREAD

**Issue by AleshaOleg** [rnicholus/beyond-jquery-book#13]
Hey, in this code:

```
stylesheet.insertRule(
    'h2 { font-weight: italic; }', stylesheet.cssRules.length - 1
);
```

We have a value - 'stylesheet', but there is no of declaration of it.

I offer, this:

```
var stylesheet = document.styleSheets[0];

stylesheet.insertRule (
	'h2{font-style:italic}', stylesheet.cssRules.length
);
```

**Comment by rnicholus** [comment]
You are correct that the `stylesheet` variable isn't defined there, but I didn't think it was important to the example. I can see adding your suggestion though. I'll revist this before I publish chapter 11.
