### ISSUE TITLE
4.2.2.2 Web API. Wrong loop

### ISSUE THREAD

**Issue by AleshaOleg** [rnicholus/beyond-jquery-book#9]
> This loop executes until we run out of previous siblings,
> starting with the sibling before the <span>. Each sibling
> is added to the allSiblings array. After this loop is complete,
> the allSiblings array will contain all siblings of the <span>
> (before and after).

```
do {
  currentElement = referenceElement.previousElementSibling;
  currentElement && allSiblings.push(currentElement);
} while (currentElement);
```

Here it's an infinite loop because every iteration `currentElement` exist, if before `<span>` we have a previous sibling. [Example](https://jsfiddle.net/AleshaOleg/r68z9jsc). If `<span>` goes first everything working fine, but as I understood this loop created to pick all of siblings.

Thanks!

**Comment by AleshaOleg** [comment]
Fixed this one.

Here it's a correct loop:
```

do {
  currentElement = currentElement.previousElementSibling;
  currentElement && allSiblings.push(currentElement);
} while (currentElement);
```

**Comment by rnicholus** [comment]
Thanks for catching this, and I noticed the same error is present in the example just below the one you referenced. I opted to also simplify that code a bit, and I'll publish an updated version now.
